server:
  port: 9004

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:root}
      url: jdbc:mysql://${MYSQL-HOST:pigx-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:zz_user}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
        cluster-name: NJ
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input:
          consumer:
            concurrency: 20
          content-type: application/json
          destination: stream-test-topic
          group: test-group1
  application:
    name: user-center


mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml

#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: zzcloud-demo1