server:
  port: 9001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:root}
      url: jdbc:mysql://${MYSQL-HOST:pigx-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:zz_content}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
        cluster-name: BJ
    sentinel:
      transport:
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
#        bindings:
#          output:
#            producer:
#              group: demo-group
      bindings:
        output:
          content-type: text/plain
          destination: stream-test-topic
  application:
    name: cont-center

mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml

logging:
  level:
    com.amay.cont.feign.RemoteUserService: debug

feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: BASIC
  #替换feign底层通信为httpclient提高性能
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true

#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: zzcloud-demo1

